config = {
    'HOST': 'x.x.x.x',
    'PORT': 11568,
    'BUFSIZ': 1024,
    'TMOUT': 1,
    'RESTART': 0,
    'MYHOSTNAME': 'my_hostname',
    'MYHOSTPASS': 'my_password',
    'PROCNAME': "gps-sender",
    'UDP_IP': "x.x.x.x",
    'UDP_PORT': 514,
    'jsonlengt': 10,
    'savefilename': 'saved',
    'trytorestart': 2,
    'debug': False,
    'GPSFAKEDATA': True,
    'alive': 60,
    'nextgps': 5,
    'reporting_url': 'http://servername/insert.php',
    'httpsend': True,
    'waitingforserveranswer': 20
}
