#!/usr/bin/env python
# -*- coding:utf-8 -*-

# from gps3 import gps3
import socket
import sys
import time
import math
import os
import json
import bz2
import random
import senderconfig as config
import subprocess
import requests as req


sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)  # for UDP logging
sock.settimeout(5)
livestream = False
li = []
jsn = int(time.time()) + config.config['jsonlengt']
circuiton = True
tryrestart = 0
withdatapacket = 0
datapacket = 0
alive = int(time.time()) + config.config['alive']


def resetdevice():
    logsend("RESET MACHINE...")
    subprocess.call("/sbin/reboot")


def restart():
    time.sleep(config.config['trytorestart'])
    python = sys.executable
    os.execl(python, python, * sys.argv)


def temperature():
    if config.config['debug']:
        logsend('SYM: Enter temperature')
    """Read device temperature."""
    return("00")


def logsend(s):
    """Write log."""
    global alive
    nt = (config.config['PROCNAME'])+" "+str((int(time.time())))+': '
    ip = config.config['UDP_IP']
    port = config.config['UDP_PORT']
    try:
        sock.sendto((nt+str(s)+'\n'), (ip, port))
        alive = int(time.time()) + config.config['alive']
    except:
        time.sleep(10)
        restart()


def devicestate():
    global circuiton
    if config.config['debug']:
        logsend('Enter devicestate procedure')
    if circuiton:
        return("eON_temp="+temperature()+(" ")+id())
    else:
        return("eOFF_temp="+temperature()+(" ")+id())


def savedata(data):
    """Save compresed packets to files because no Internet"""
    if config.config['debug']:
        logsend('Data will be saved...')
    filename = (config.config['savefilename'])+str(int(time.time()))
    plik = open(filename, 'wb')
    plik.write(data)
    plik.close()
    if config.config['debug']:
        logsend(str(filename)+" with data saved")


def loaddata(tcpCliSock='0'):
    global tryrestart
    if config.config['debug']:
        logsend('Enter to loaddata procedure...')
    li = []
    for a in os.listdir('.'):
        if (a[:(len(config.config['savefilename']))]) == (config.config['savefilename']):
            li.append(a)
    for a in li:
        plik = open(a, 'rb')
        if config.config['debug']:
            logsend('File '+a+' opened...')
        tekst = plik.read()
        plik.close()
        if config.config['httpsend']:
            hs = httpsend(tekst)
            switch(hs, 1)
            if httpsend(tekst) != "error":
                os.remove(a)
                logsend(str(a)+" deleted")
        else:
            try:
                tcpCliSock.send(tekst)
                if config.config['debug']:
                    logsend('File '+a+' sended')
                os.remove(a)
                logsend(str(a)+" deleted")
            except:
                if config.config['debug']:
                    logsend('Error manipulation with file '+a+'')
                    return()
            if switch(tcpCliSock):
                pass
            else:
                return()
        if config.config['debug']:
            logsend('remote info from server recieved')
    tryrestart = 0


def entry(packet):
    if config.config['debug']:
        logsend('Creating json packet')
    entry = {
        "time": packet.split()[0],
        "longitude": packet.split()[1],
        "latitude": packet.split()[2],
        "state": str(packet.split()[3]),
        "deviceid": str(packet.split()[4]),
    }
    return(entry)


def switch(tcpCliSock, h=False):
    if config.config['debug']:
        logsend("enter switch procedure")
        if h:
            logsend("in http mode")
    global livestream
    global circuiton
    wh = True
    servanswer = 0
    if h:
        if (tcpCliSock == "error"):
            return(False)
        recv = tcpCliSock
    else:
        while wh:
            try:
                recv = tcpCliSock.recv(1024)
                wh = False
            except:
                logsend("waiting for server answer")
                servanswer += 1
                if (servanswer > config.config['waitingforserveranswer']):
                    restart()
                time.sleep(0.1)
    if config.config['debug']:
        logsend("recv = "+recv)
    if recv == ("ok"):
        livestream = True
        if config.config['debug']:
            logsend("livestream is True")
        return(True)
    if recv == ("no"):
        livestream = False
        if config.config['debug']:
            logsend("livestream is False")
        return(True)
    if recv == ("off"):
        logsend("SYM: circuit off message was recieved")
        # gpio.output(port.PG9, gpio.LOW)
        circuiton = False
        return(True)
    if recv == ("on"):
        logsend("SYM: circuit ON !!!")
        # gpio.output(port.PG9, gpio.HIGH)
        circuiton = True
        return(True)
    if recv == ("restart"):
        restart()
        return(True)
    if recv == ("reset"):
        resetdevice()
        return(True)
    else:
        logsend("no data from server")
        return(False)


def httpsend(data):
    try:
        r = req.post(config.config['reporting_url'], data=data, headers={'Content-Type': 'application/x-www-form-urlencoded'})
    except:
        return("error")
    return(r.text)


def sendingdata(tcpCliSock, data):
    global jsn
    global tryrestart
    global livestream
    global alive
    global datapacket
    global withdatapacket
    if config.config['debug']:
        logsend('Enter sendingdata procedure data = '+str(data))
    dataheader = str("short ")
    datasend = dataheader+data
    # livestream = True
    if tcpCliSock == ("offline"):
        livestream = False
    if livestream:
        if config.config['debug']:
            logsend('sendingdata:  livestream is TRUE')
        if config.config['httpsend']:
            logsend("preparing short json packet")
            compdata = bz2.compress(datasend)
            hs = httpsend(compdata)
            logsend(hs)
            switch(hs, 1)
            if (hs == "error"):
                logsend("error with http "+datasend)
        else:
            try:
                if config.config['debug']:
                    logsend('sendingdata:  try sending')
                tcpCliSock.send(datasend)
                if config.config['debug']:
                    logsend('sendingdata:  sending OK')
                if config.config['debug']:
                    logsend("small packet was send to server...")
                if not switch(tcpCliSock):
                    restart()
            except socket.error, msg:
                if config.config['debug']:
                    logsend('sendingdata:  socket ERROR')
                logsend("socket errot -> "+str(msg))
                logsend("lost packet -> "+str(datasend))
                restart()
    else:
        if config.config['debug']:
            logsend('sendingdata:  no livestream and append data')
        li.append(data)
        data1 = data.split(" ")
        if ((data1[1]) != "99.999999999") and ((data1[1]) != "n/a"):
            if config.config['debug']:
                logsend('sendingdata:  packet is TRUE')
            withdatapacket += 1
        if config.config['debug']:
            logsend(str(jsn)+' = jsn time = '+str(int(time.time())))
            logsend(str(datapacket)+' = data wdata = '+str(withdatapacket))
        tm = int(time.time())
        if (jsn < tm) or (math.fabs(jsn-tm) > (config.config['jsonlengt']+20)):
            if config.config['debug']:
                logsend('sendingdata:  json packet is FULL')
            if withdatapacket == 0:
                if config.config['debug']:
                    logsend('sendingdata: in json no packet with real data')
                datapacket += 1
            else:
                datapacket = 0
            withdatapacket = 0
            if datapacket > 4:
                if config.config['debug']:
                    logsend('sendingdata:  to many packet with no real data')
                resetdevice()
            li.reverse()
            if config.config['debug']:
                logsend('sendingdata:  reversing list')
            packet = []
            while li != []:
                packet.append(entry(li.pop()))
            if config.config['debug']:
                logsend('sendingdata:  compression data')
            compdata = bz2.compress(json.dumps(packet))
            if tcpCliSock == ("offline"):
                savedata(compdata)
                if tryrestart > config.config['trytorestart']:
                    restart()
                tryrestart += 1
            else:
                if config.config['debug']:
                    logsend('sendingdata:  going to sending compress data')
                #  send ing data via http
                if config.config['httpsend']:
                    hs = httpsend(compdata)
                    switch(hs, 1)
                    logsend(hs)
                    if (hs != "error"):
                        loaddata()
                    else:
                        savedata(compdata)
                else:
                    try:
                        #  sending 2 server via tcpCliSock
                        tcpCliSock.send(compdata)
                        if config.config['debug']:
                            logsend("send data OK")
                        #  recieving data from server
                        if switch(tcpCliSock):
                            if config.config['debug']:
                                logsend("Data was recieved by server")
                            loaddata(tcpCliSock)
                        else:
                            logsend("Data was not recieved by server")
                            savedata(compdata)
                    except:
                        logsend("send or recv data FALSE")
                        savedata(compdata)
                        if tryrestart > config.config['trytorestart']:
                            restart()
                        tryrestart += 1
            jsn = int(time.time()) + config.config['jsonlengt']
            if config.config['debug']:
                logsend('sendingdata:  new json-end value')
        if config.config['debug']:
            logsend('sendingdata:  end of procedure')


def id():
    return(config.config['deviceid'])


def sendergps(tcpCliSock):
    global alive
    if config.config['debug']:
        logsend('Enter senderGPS procedure')
    while True:
        if int(time.time()) > alive:
            logsend('alive temp='+temperature())
            d = str(int(time.time()))+(" 99.999999999 99.999999999 ")
            sendingdata(tcpCliSock, d+devicestate())
            if config.config['debug']:
                logsend('return from sendingdata (perdiodic fake data)')
        else:
            if config.config['GPSFAKEDATA']:
                d0 = str(int(time.time()))+(" 21.")
                d1 = str(random.random())[2:11]+(" 52.")
                d2 = str(random.random())[2:11]+(" ")+devicestate()
                sendingdata(tcpCliSock, d0+d1+d2)
                if config.config['debug']:
                    logsend('return from sendingdata (data from random)')
                time.sleep(1)


def tcpinit():
    tcpCliSock = None
    for res in socket.getaddrinfo(config.config['HOST'], config.config['PORT'], socket.AF_UNSPEC, socket.SOCK_STREAM):
        af, socktype, proto, canonname, sa = res
        try:
            tcpCliSock = socket.socket(af, socktype, proto)
            logsend('Preparing data socket:')
            tcpCliSock.settimeout(config.config['TMOUT'])
            logsend('Preparing networksocket options')
        except socket.error, msg:
            logsend(msg)
            tcpCliSock = None

        try:
            tcpCliSock.connect(sa)
            destin = (' to port: ')+str(config.config['PORT'])
            logsend("".join('Connection from: ')+str(config.config['HOST'])+destin)
        except socket.error, msg:
            logsend('cannot be connection establish')
            tcpCliSock.close()
            tcpCliSock = None
            continue
        break

    if tcpCliSock is None:
        logsend('cannot be data socket established !')
        logsend('working in offline mode')
        sendergps("offline")
    else:
        logsend('Data socket ready !!!')

    data = "gps"
    tcpCliSock.send(data)
    try:
        data = tcpCliSock.recv(1024)
    except:
        restart()
    logsend(data)
    if data == ("gps mode OK"):
        sendergps(tcpCliSock)
        tcpCliSock.close()
    logsend('remote server closed')
    restart()


def main():
    if config.config['httpsend']:
        logsend("sendergps in HTTP mode lets'go")
        sendergps("http")
    else:
        logsend("sendergps in TCP mode lets'go")
        tcpinit()


if __name__ == '__main__':
    sys.exit(main())
